[emacs.font]
size = 20
family = "IosevkaSS04 Nerd Font Mono"

[alacritty.font]
size = 16
family = "IosevkaSS04 Nerd Font Mono"

[notes.vault]
path = ""

[pi]
path = "~/.pi/"

[git]
name = "Matheus Lima"
email = "matheus.limastack@gmail.com"
signingkey = "19604D1434714668F81161E1D25619C31A4270DE"
