[".zsh/oh-my-zsh"]
    type = "git-repo"
    url = "https://github.com/ohmyzsh/ohmyzsh.git"
    exact = true
    stripComponents = 1

[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/mateusfdl/nvim.git"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

