general {
    lock_cmd = quickshell ipc call lockscreen lock
    before_sleep_cmd = loginctl lock-session    
    after_sleep_cmd = hyprctl dispatch dpms on 
    ignore_dbus_inhibit = false             
}

listener {
    timeout = 1200                     
    on-timeout = loginctl lock-session
}
