source = ~/.config/hypr/monitors.conf

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_QUICK_CONTROLS_STYLE,Basic
env = QML2_IMPORT_PATH,$HOME/.config/quickshell/plugin/build/qml
env = GDK_BACKEND,wayland,x11,*

env = NIXOS_OZONE_WL,1

env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct
env = WLR_NO_HARDWARE_CURSORS,1

env = XCURSOR_THEME,macOS
env = XCURSOR_SIZE,24
env = HYPRCURSOR_THEME,macOS
env = HYPRCURSOR_SIZE,24

exec-once = qs -p ~/.config/quickshell/greeter.qml

general {
    gaps_in = 0
    gaps_out = 0
    border_size = 0
}

decoration {
    rounding = 0
    blur {
        enabled = false
    }
    shadow {
        enabled = false
    }
}

animations {
    enabled = false
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
    vfr = true
}

input {
    kb_layout = us
    follow_mouse = 1
}

bind = CTRL ALT, Delete, exit
