-- Generated by nwg-displays on 2026-07-19 at 00:37:55. Do not edit manually.

hl.monitor({
    output = "DP-3",
    mode = "3840x2160@60.0",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "DP-4",
    mode = "3840x2160@60.0",
    position = "3840x0",
    scale = 1.0
})
