# Based on nwg-displays output, manually adjusted.
# DP-4: 3840x2160 (4K, left) -- primary workspaces
# DP-3: 2560x1440 (right) -- secondary workspaces

workspace=1,monitor:DP-4,default:true
workspace=2,monitor:DP-4
workspace=3,monitor:DP-4
workspace=4,monitor:DP-4
workspace=5,monitor:DP-3,default:true
workspace=6,monitor:DP-3
workspace=7,monitor:DP-3
workspace=8,monitor:DP-3
workspace=9,monitor:DP-3
workspace=10,monitor:DP-3
