#!/usr/bin/env bash
set -euo pipefail

docker ps >/dev/null || exit 1

VERSION="26.0.2"
STYLE="${1:-ss04}"
RELEASE_URL="https://github.com/be5invis/Iosevka/releases/download/v$VERSION/ttf-iosevka-$STYLE-$VERSION.zip"

OUTDIR="${2:-$PWD/patched-iosevka-$STYLE}"

TEMPDIR=$(mktemp -d)
trap 'rm -rf "$TEMPDIR"' EXIT

{
  curl -fLo "$TEMPDIR/iosevka.zip" "$RELEASE_URL"
  mkdir -p "$TEMPDIR/extract" "$TEMPDIR/in" "$TEMPDIR/out"
  unzip -q "$TEMPDIR/iosevka.zip" -d "$TEMPDIR/extract"
  find "$TEMPDIR/extract" -name '*.ttf' -exec mv {} "$TEMPDIR/in" \;

  docker run \
    --rm \
    -v "$TEMPDIR/in:/in" \
    -v "$TEMPDIR/out:/out" nerdfonts/patcher \
    --complete \
    --use-single-width-glyphs
} >&2

mkdir -p "$OUTDIR"
cp "$TEMPDIR"/out/* "$OUTDIR"

echo "$OUTDIR"
