source = $HOME/.config/hypr/wallust/wallust-hyprland.conf

general {
  border_size = 1
  gaps_in = 2
  gaps_out = 20

  col.active_border = rgba(ffffff1a)
  col.inactive_border = rgba(ffffff0d)
}

decoration {
  rounding = 12

  active_opacity = 1.0
  inactive_opacity = 1.0
  fullscreen_opacity = 1.0

  dim_inactive = true
  dim_strength = 0.15
  dim_special = 0.8

  shadow {
    enabled = true
    range = 35
    render_power = 2
    sharp = false
    offset = 0 9
    scale = 1.0

    color = rgba(00000059)
    color_inactive = rgba(00000026)
  }

  blur {
    enabled = true
    size = 6
    passes = 2
    ignore_opacity = true
    new_optimizations = true
    special = true
    popups = true
    xray = true
  }
}

group {
    col.border_active = $color15

    groupbar {
        col.active = $color0
    }
}
