$mainMod = SUPER
$scripts = $HOME/.config/hypr/scripts
$term = kitty
$files = nautilus

# App launchers
bind = $mainMod, D, global, quickshell:launcherToggle
bind = $mainMod, B, exec, xdg-open "https://"
bind = $mainMod, A, global, quickshell:overviewToggle
bind = $mainMod, Return, exec, $term
bind = $mainMod, E, exec, $files

# Refresh hyprland config
bind = $mainMod ALT, R, exec, hyprctl reload

# Window management
bind = $mainMod SHIFT, F, fullscreen
bind = $mainMod CTRL, F, fullscreen, 1
bind = $mainMod, SPACE, togglefloating,
bind = $mainMod ALT, SPACE, exec, hyprctl dispatch workspaceopt allfloat

# Opacity toggle on active window
bind = $mainMod CTRL, O, exec, hyprctl setprop active opaque toggle

# Cursor zoom
bind = $mainMod ALT, mouse_down, exec, hyprctl keyword cursor:zoom_factor "$(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = $2; if (factor < 1) {factor = 1}; print factor * 2.0}')"
bind = $mainMod ALT, mouse_up, exec, hyprctl keyword cursor:zoom_factor "$(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = $2; if (factor < 1) {factor = 1}; print factor / 2.0}')"

bind = ALT, TAB, global, quickshell:windowSwitcherNext
bind = ALT SHIFT, TAB, global, quickshell:windowSwitcherPrevious
bindr = ALT, ALT_L, global, quickshell:windowSwitcherActivate
bind = ,mouse:277, global, quickshell:cheatsheetToggle
bind = $mainMod, T, global, quickshell:obsidianTodoToggle
bind = $mainMod SHIFT, T, global, quickshell:dailyTodosToggle
