{ pkgs, claude-desktop-pkg, ... }:
{
  environment.systemPackages = with pkgs; [
    apple-cursor
    brave
    brightnessctl
    cliphist
    git
    glib
    gnupg
    grim
    hyprcursor
    hypridle
    hyprwayland-scanner
    hyprwire
    kdePackages.qt6ct
    kitty
    libsForQt5.qt5ct
    mpv
    networkmanagerapplet
    nwg-displays
    papirus-icon-theme
    pavucontrol
    qt6.qt5compat
    qt6.qtdeclarative
    qt6.qttools
    qt6.qtwayland
    quickshell
    slurp
    awww
    tmux
    tree-sitter
    unzip
    vim
    wget
    wf-recorder
    wl-clipboard
    wireguard-tools
  ];

  users.users.matheus.packages = with pkgs; [
    claude-desktop-pkg
    discord
    gh
    morgen
    obsidian
    spotify
    btop
  ];
}
